### ISSUE TITLE
The scores directory.

### ISSUE THREAD

**Issue by amd-rezaei** [EdenBelouadah/class-incremental-learning#7]
Hi Eden,
I am trying to reproduce your results with your code and use these valuable methods that you have published. However, I cannot find `fine_tuning_scores_path` directory in the shared dataset. I would appreciate it if you could provide me with that or explain how I can reproduce it.

Keep up the good work!

**Comment by EdenBelouadah** [comment]
Hello Ahmad and thank you for your interest in our codes. I unfortunately can't provide you with the raw scores because I left my lab and I can't access to the files anymore. However, you can produce them by running the features_extraction.py code. It consists in taking the models trained with fine tuning, and extract the features and prediction scores for the training and testing images.

**Comment by amd-rezaei** [comment]
Hello Eden,
Thank you for taking the time and answering me. I would definitely try that out.
